package com.telcobright.billing.data;

import com.telcobright.billing.mediation.cdr.CdrRowSql;
import com.telcobright.billing.mediation.engine.models.acc_chargeable;
import com.telcobright.billing.mediation.sql.SqlDialect;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The DDL file ({@code sql/postgres/billing-tables.sql}) is the one source of the tables' columns; the writers'
 * column lists are checked against it here, so the two cannot drift. And the statements {@link PostgresTenantTables}
 * makes from it — a table with ALL its partitions in one step, the rights, a month added by moving — are pinned as
 * text (what PostgreSQL makes of them is {@code PostgresTenantTablesLabTests}).
 */
class PostgresTablesDdlTests {

    private static final Map<String, List<String>> Ddl = PostgresTenantTables.ReadTheDdl();

    /** The column names of a {@code CREATE TABLE x ( … )} statement, as written (not lower-cased). */
    private static List<String> ColumnsOf(String createTable) {
        String body = createTable.substring(createTable.indexOf('(') + 1, createTable.lastIndexOf(") PARTITION BY"));
        List<String> names = new ArrayList<>();
        for (String line : body.split("\n")) {
            String def = line.strip();
            if (def.isEmpty() || def.toUpperCase().startsWith("PRIMARY KEY")) continue;
            names.add(def.split("\\s+")[0]);
        }
        return names;
    }

    private static PostgresTenantTables TablesOn(LocalDate today) {
        return new PostgresTenantTables(PostgresTenantTables.Options.Defaults(), () -> today);
    }

    @Test
    void the_cdr_table_has_exactly_the_columns_the_writer_emits_in_its_order() {
        String createCdr = Ddl.get("table cdr").get(0);

        assertEquals(List.of(CdrRowSql.Columns(SqlDialect.PostgreSql).split(",")), ColumnsOf(createCdr));
        assertTrue(createCdr.endsWith("PARTITION BY RANGE (StartTime)"), "partitioned on the row's time");
    }

    @Test
    void cdrerror_has_cdrs_columns_by_construction() {
        assertEquals(List.of("CREATE TABLE cdrerror (LIKE cdr) PARTITION BY RANGE (StartTime)"), Ddl.get("table cdrerror"));
    }

    @Test
    void the_chargeable_table_has_exactly_the_columns_the_writer_emits_in_its_order() {
        String create = Ddl.get("table acc_chargeable").get(0);

        assertEquals(List.of(acc_chargeable.ExtInsertColumns.split(",")), ColumnsOf(create));
        assertTrue(create.endsWith("PARTITION BY RANGE (transactionTime)"));
    }

    @Test
    void the_outbox_table_has_the_four_columns_the_summary_service_reads_and_ids_one_at_a_time() {
        String create = Ddl.get("table summary_affected").get(0);

        for (String column : List.of("id ", "entity_type ", "op ", "data ")) assertTrue(create.contains(column), column);
        assertTrue(create.contains("GENERATED BY DEFAULT AS IDENTITY (CACHE 1)"),
                "the ids must stay in commit order: no session may hold a block of them");
        assertFalse(create.contains("PARTITION"), "the outbox is not partitioned");
    }

    @Test
    void the_times_are_without_time_zone_and_the_meta_data_is_text_not_jsonb() {
        String createCdr = Ddl.get("table cdr").get(0);

        assertTrue(createCdr.matches("(?s).*StartTime\\s+timestamp\\s+NOT NULL.*"));
        assertFalse(createCdr.toLowerCase().contains("timestamptz") || createCdr.toLowerCase().contains("with time zone"));
        assertTrue(createCdr.matches("(?s).*AdditionalMetaData\\s+text.*"), "the reader matches the producer's own spelling");
        assertFalse(createCdr.toLowerCase().contains("varchar"), "no length can refuse a row");
    }

    @Test
    void a_table_is_made_in_one_step_with_all_its_partitions_then_its_indexes_then_its_rights() {
        List<String> step = TablesOn(LocalDate.of(2026, 10, 4)).StatementsToCreate(List.of("cdr"), YearMonth.of(2026, 10));

        assertTrue(step.get(0).startsWith("CREATE TABLE cdr ("));
        assertEquals(List.of(
                "CREATE TABLE cdr_p202609 PARTITION OF cdr FOR VALUES FROM ('2026-09-01 00:00:00') TO ('2026-10-01 00:00:00')",
                "CREATE TABLE cdr_p202610 PARTITION OF cdr FOR VALUES FROM ('2026-10-01 00:00:00') TO ('2026-11-01 00:00:00')",
                "CREATE TABLE cdr_p202611 PARTITION OF cdr FOR VALUES FROM ('2026-11-01 00:00:00') TO ('2026-12-01 00:00:00')",
                "CREATE TABLE cdr_p202612 PARTITION OF cdr FOR VALUES FROM ('2026-12-01 00:00:00') TO ('2027-01-01 00:00:00')",
                "CREATE TABLE cdr_p202701 PARTITION OF cdr FOR VALUES FROM ('2027-01-01 00:00:00') TO ('2027-02-01 00:00:00')",
                "CREATE TABLE cdr_pdefault PARTITION OF cdr DEFAULT"), step.subList(1, 7));
        assertEquals("CREATE UNIQUE INDEX ux_cdr_call ON cdr (ChannelCallUuid, StartTime)", step.get(7));
        int rights = step.indexOf("REVOKE ALL ON cdr FROM summary_service");
        assertTrue(rights > 7, "the rights come after the indexes: " + step);
        assertEquals(List.of(
                "REVOKE ALL ON cdr FROM summary_service",
                "GRANT SELECT ON cdr TO summary_service",
                "REVOKE ALL ON cdr_p202609 FROM summary_service",
                "REVOKE ALL ON cdr_p202610 FROM summary_service",
                "REVOKE ALL ON cdr_p202611 FROM summary_service",
                "REVOKE ALL ON cdr_p202612 FROM summary_service",
                "REVOKE ALL ON cdr_p202701 FROM summary_service",
                "REVOKE ALL ON cdr_pdefault FROM summary_service",
                "GRANT SELECT ON cdr TO ad_sphere"), step.subList(rights, step.size()));
    }

    @Test
    void the_summary_service_may_delete_from_the_outbox_and_from_nothing_else() {
        PostgresTenantTables tables = TablesOn(LocalDate.of(2026, 10, 4));

        assertEquals(List.of("REVOKE ALL ON summary_affected FROM summary_service",
                "GRANT SELECT, DELETE ON summary_affected TO summary_service",
                "GRANT SELECT ON summary_affected TO ad_sphere"), tables.RightsOn("summary_affected", List.of()));
        for (String table : List.of("cdr", "cdrerror", "acc_chargeable"))
            assertTrue(tables.RightsOn(table, List.of()).contains("GRANT SELECT ON " + table + " TO summary_service"), table);
    }

    @Test
    void the_role_names_and_the_window_are_the_profiles() {
        var tables = new PostgresTenantTables(new PostgresTenantTables.Options("sum_ro", List.of("ads", "audit"), 0, 1),
                () -> LocalDate.of(2026, 12, 31));

        List<String> step = tables.StatementsToCreate(List.of("acc_chargeable"), YearMonth.of(2026, 12));

        assertTrue(step.contains("CREATE TABLE acc_chargeable_p202612 PARTITION OF acc_chargeable FOR VALUES FROM ('2026-12-01 00:00:00') TO ('2027-01-01 00:00:00')"));
        assertTrue(step.contains("CREATE TABLE acc_chargeable_p202701 PARTITION OF acc_chargeable FOR VALUES FROM ('2027-01-01 00:00:00') TO ('2027-02-01 00:00:00')"));
        assertFalse(step.stream().anyMatch(s -> s.contains("_p202611")), "months-back is 0");
        assertFalse(step.stream().anyMatch(s -> s.contains("_p202702")), "months-ahead is 1");
        assertTrue(step.contains("GRANT SELECT ON acc_chargeable TO sum_ro"));
        assertTrue(step.contains("GRANT SELECT ON acc_chargeable TO ads") && step.contains("GRANT SELECT ON acc_chargeable TO audit"));
    }

    @Test
    void no_role_named_means_no_grant_and_no_revoke() {
        var tables = new PostgresTenantTables(new PostgresTenantTables.Options("", List.of(), 1, 3), () -> LocalDate.of(2026, 10, 4));

        List<String> step = tables.StatementsToCreate(List.of("cdr", "summary_affected"), YearMonth.of(2026, 10));

        assertFalse(step.stream().anyMatch(s -> s.startsWith("GRANT") || s.startsWith("REVOKE")), step.toString());
    }

    @Test
    void a_role_name_that_is_not_one_is_refused_before_it_reaches_a_statement() {
        IllegalStateException e = assertThrows(IllegalStateException.class,
                () -> new PostgresTenantTables.Options("summary_service; DROP TABLE cdr", List.of(), 1, 3));

        assertTrue(e.getMessage().contains("is not a PostgreSQL role name"), e.getMessage());
    }

    @Test
    void a_month_is_added_by_moving_what_the_default_partition_holds_of_it() {
        List<String> step = TablesOn(LocalDate.of(2026, 10, 4)).StatementsToAddAMonth("cdr", YearMonth.of(2027, 2));

        assertEquals(List.of(
                "SET LOCAL lock_timeout = '5s'",
                "CREATE TABLE cdr_p202702 (LIKE cdr INCLUDING DEFAULTS)",
                "WITH moved AS (DELETE FROM cdr_pdefault WHERE StartTime >= '2027-02-01 00:00:00' AND StartTime < '2027-03-01 00:00:00'"
                        + " RETURNING *) INSERT INTO cdr_p202702 SELECT * FROM moved",
                "ALTER TABLE cdr ATTACH PARTITION cdr_p202702 FOR VALUES FROM ('2027-02-01 00:00:00') TO ('2027-03-01 00:00:00')",
                "REVOKE ALL ON cdr_p202702 FROM summary_service"), step);
    }
}
