-- ============================================================================
-- LOCAL DEBUG schema for the CDR-processing -> summary-outbox WRITE PATH.
-- PERMISSIVE (columns are TEXT/BIGINT, types NOT enforced) — proves the write
-- path (rows land, blob encodes, one tx) on a throwaway local MySQL. NOT the
-- production schema; for faithful type behaviour run against the real CCL schema.
-- Generated from cdr/acc_chargeable ExtInsertColumns (keep regenerated if they change).
--
-- Apply:
--   mysql -h 127.0.0.1 -P 3306 -u root -p123456 -e 'create database if not exists ccl_debug'
--   mysql -h 127.0.0.1 -P 3306 -u root -p123456 ccl_debug < docs/local-debug-schema.sql
-- then set profile-dev.yml datasource -> host 127.0.0.1, database ccl_debug, user root, password 123456.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cdr (
  `SwitchId` TEXT NULL,
  `IdCall` BIGINT NULL,
  `SequenceNumber` TEXT NULL,
  `FileName` TEXT NULL,
  `ServiceGroup` TEXT NULL,
  `IncomingRoute` TEXT NULL,
  `OriginatingIP` TEXT NULL,
  `OPC` TEXT NULL,
  `OriginatingCIC` TEXT NULL,
  `OriginatingCalledNumber` TEXT NULL,
  `TerminatingCalledNumber` TEXT NULL,
  `OriginatingCallingNumber` TEXT NULL,
  `TerminatingCallingNumber` TEXT NULL,
  `PrePaid` TEXT NULL,
  `DurationSec` TEXT NULL,
  `EndTime` TEXT NULL,
  `ConnectTime` TEXT NULL,
  `AnswerTime` TEXT NULL,
  `ChargingStatus` TEXT NULL,
  `PDD` TEXT NULL,
  `CountryCode` TEXT NULL,
  `AreaCodeOrLata` TEXT NULL,
  `ReleaseDirection` TEXT NULL,
  `ReleaseCauseSystem` TEXT NULL,
  `ReleaseCauseEgress` TEXT NULL,
  `OutgoingRoute` TEXT NULL,
  `TerminatingIP` TEXT NULL,
  `DPC` TEXT NULL,
  `TerminatingCIC` TEXT NULL,
  `StartTime` TEXT NULL,
  `InPartnerId` TEXT NULL,
  `CustomerRate` TEXT NULL,
  `OutPartnerId` TEXT NULL,
  `SupplierRate` TEXT NULL,
  `MatchedPrefixY` TEXT NULL,
  `UsdRateY` TEXT NULL,
  `MatchedPrefixCustomer` TEXT NULL,
  `MatchedPrefixSupplier` TEXT NULL,
  `InPartnerCost` TEXT NULL,
  `OutPartnerCost` TEXT NULL,
  `CostAnsIn` TEXT NULL,
  `CostIcxIn` TEXT NULL,
  `Tax1` TEXT NULL,
  `IgwRevenueIn` TEXT NULL,
  `RevenueAnsOut` TEXT NULL,
  `RevenueIgwOut` TEXT NULL,
  `RevenueIcxOut` TEXT NULL,
  `Tax2` TEXT NULL,
  `XAmount` TEXT NULL,
  `YAmount` TEXT NULL,
  `AnsPrefixOrig` TEXT NULL,
  `AnsIdOrig` TEXT NULL,
  `AnsPrefixTerm` TEXT NULL,
  `AnsIdTerm` TEXT NULL,
  `ValidFlag` TEXT NULL,
  `PartialFlag` TEXT NULL,
  `ReleaseCauseIngress` TEXT NULL,
  `InRoamingOpId` TEXT NULL,
  `OutRoamingOpId` TEXT NULL,
  `CalledPartyNOA` TEXT NULL,
  `CallingPartyNOA` TEXT NULL,
  `AdditionalSystemCodes` TEXT NULL,
  `AdditionalPartyNumber` TEXT NULL,
  `ResellerIds` TEXT NULL,
  `ZAmount` TEXT NULL,
  `PreviousRoutes` TEXT NULL,
  `E1Id` TEXT NULL,
  `MediaIp1` TEXT NULL,
  `MediaIp2` TEXT NULL,
  `MediaIp3` TEXT NULL,
  `MediaIp4` TEXT NULL,
  `CallReleaseDuration` TEXT NULL,
  `E1IdOut` TEXT NULL,
  `InTrunkAdditionalInfo` TEXT NULL,
  `OutTrunkAdditionalInfo` TEXT NULL,
  `InMgwId` TEXT NULL,
  `OutMgwId` TEXT NULL,
  `MediationComplete` TEXT NULL,
  `Codec` TEXT NULL,
  `ConnectedNumberType` TEXT NULL,
  `RedirectingNumber` TEXT NULL,
  `CallForwardOrRoamingType` TEXT NULL,
  `OtherDate` TEXT NULL,
  `SummaryMetaTotal` TEXT NULL,
  `TransactionMetaTotal` TEXT NULL,
  `ChargeableMetaTotal` TEXT NULL,
  `ErrorCode` TEXT NULL,
  `NERSuccess` TEXT NULL,
  `RoundedDuration` TEXT NULL,
  `PartialDuration` TEXT NULL,
  `PartialAnswerTime` TEXT NULL,
  `PartialEndTime` TEXT NULL,
  `FinalRecord` TEXT NULL,
  `Duration1` TEXT NULL,
  `Duration2` TEXT NULL,
  `Duration3` TEXT NULL,
  `Duration4` TEXT NULL,
  `PreviousPeriodCdr` TEXT NULL,
  `UniqueBillId` TEXT NULL,
  `AdditionalMetaData` TEXT NULL,
  `Category` TEXT NULL,
  `SubCategory` TEXT NULL,
  `ChangedByJobId` TEXT NULL,
  `SignalingStartTime` TEXT NULL
);

CREATE TABLE IF NOT EXISTS cdrerror (
  `SwitchId` TEXT NULL,
  `IdCall` BIGINT NULL,
  `SequenceNumber` TEXT NULL,
  `FileName` TEXT NULL,
  `ServiceGroup` TEXT NULL,
  `IncomingRoute` TEXT NULL,
  `OriginatingIP` TEXT NULL,
  `OPC` TEXT NULL,
  `OriginatingCIC` TEXT NULL,
  `OriginatingCalledNumber` TEXT NULL,
  `TerminatingCalledNumber` TEXT NULL,
  `OriginatingCallingNumber` TEXT NULL,
  `TerminatingCallingNumber` TEXT NULL,
  `PrePaid` TEXT NULL,
  `DurationSec` TEXT NULL,
  `EndTime` TEXT NULL,
  `ConnectTime` TEXT NULL,
  `AnswerTime` TEXT NULL,
  `ChargingStatus` TEXT NULL,
  `PDD` TEXT NULL,
  `CountryCode` TEXT NULL,
  `AreaCodeOrLata` TEXT NULL,
  `ReleaseDirection` TEXT NULL,
  `ReleaseCauseSystem` TEXT NULL,
  `ReleaseCauseEgress` TEXT NULL,
  `OutgoingRoute` TEXT NULL,
  `TerminatingIP` TEXT NULL,
  `DPC` TEXT NULL,
  `TerminatingCIC` TEXT NULL,
  `StartTime` TEXT NULL,
  `InPartnerId` TEXT NULL,
  `CustomerRate` TEXT NULL,
  `OutPartnerId` TEXT NULL,
  `SupplierRate` TEXT NULL,
  `MatchedPrefixY` TEXT NULL,
  `UsdRateY` TEXT NULL,
  `MatchedPrefixCustomer` TEXT NULL,
  `MatchedPrefixSupplier` TEXT NULL,
  `InPartnerCost` TEXT NULL,
  `OutPartnerCost` TEXT NULL,
  `CostAnsIn` TEXT NULL,
  `CostIcxIn` TEXT NULL,
  `Tax1` TEXT NULL,
  `IgwRevenueIn` TEXT NULL,
  `RevenueAnsOut` TEXT NULL,
  `RevenueIgwOut` TEXT NULL,
  `RevenueIcxOut` TEXT NULL,
  `Tax2` TEXT NULL,
  `XAmount` TEXT NULL,
  `YAmount` TEXT NULL,
  `AnsPrefixOrig` TEXT NULL,
  `AnsIdOrig` TEXT NULL,
  `AnsPrefixTerm` TEXT NULL,
  `AnsIdTerm` TEXT NULL,
  `ValidFlag` TEXT NULL,
  `PartialFlag` TEXT NULL,
  `ReleaseCauseIngress` TEXT NULL,
  `InRoamingOpId` TEXT NULL,
  `OutRoamingOpId` TEXT NULL,
  `CalledPartyNOA` TEXT NULL,
  `CallingPartyNOA` TEXT NULL,
  `AdditionalSystemCodes` TEXT NULL,
  `AdditionalPartyNumber` TEXT NULL,
  `ResellerIds` TEXT NULL,
  `ZAmount` TEXT NULL,
  `PreviousRoutes` TEXT NULL,
  `E1Id` TEXT NULL,
  `MediaIp1` TEXT NULL,
  `MediaIp2` TEXT NULL,
  `MediaIp3` TEXT NULL,
  `MediaIp4` TEXT NULL,
  `CallReleaseDuration` TEXT NULL,
  `E1IdOut` TEXT NULL,
  `InTrunkAdditionalInfo` TEXT NULL,
  `OutTrunkAdditionalInfo` TEXT NULL,
  `InMgwId` TEXT NULL,
  `OutMgwId` TEXT NULL,
  `MediationComplete` TEXT NULL,
  `Codec` TEXT NULL,
  `ConnectedNumberType` TEXT NULL,
  `RedirectingNumber` TEXT NULL,
  `CallForwardOrRoamingType` TEXT NULL,
  `OtherDate` TEXT NULL,
  `SummaryMetaTotal` TEXT NULL,
  `TransactionMetaTotal` TEXT NULL,
  `ChargeableMetaTotal` TEXT NULL,
  `ErrorCode` TEXT NULL,
  `NERSuccess` TEXT NULL,
  `RoundedDuration` TEXT NULL,
  `PartialDuration` TEXT NULL,
  `PartialAnswerTime` TEXT NULL,
  `PartialEndTime` TEXT NULL,
  `FinalRecord` TEXT NULL,
  `Duration1` TEXT NULL,
  `Duration2` TEXT NULL,
  `Duration3` TEXT NULL,
  `Duration4` TEXT NULL,
  `PreviousPeriodCdr` TEXT NULL,
  `UniqueBillId` TEXT NULL,
  `AdditionalMetaData` TEXT NULL,
  `Category` TEXT NULL,
  `SubCategory` TEXT NULL,
  `ChangedByJobId` TEXT NULL,
  `SignalingStartTime` TEXT NULL
);

CREATE TABLE IF NOT EXISTS acc_chargeable (
  `id` BIGINT NULL,
  `uniqueBillId` TEXT NULL,
  `idEvent` TEXT NULL,
  `transactionTime` TEXT NULL,
  `assignedDirection` TEXT NULL,
  `description` TEXT NULL,
  `glAccountId` TEXT NULL,
  `servicegroup` TEXT NULL,
  `servicefamily` TEXT NULL,
  `ProductId` TEXT NULL,
  `idBilledUom` TEXT NULL,
  `idQuantityUom` TEXT NULL,
  `BilledAmount` TEXT NULL,
  `Quantity` TEXT NULL,
  `unitPriceOrCharge` TEXT NULL,
  `Prefix` TEXT NULL,
  `RateId` TEXT NULL,
  `TaxAmount1` TEXT NULL,
  `TaxAmount2` TEXT NULL,
  `TaxAmount3` TEXT NULL,
  `VatAmount1` TEXT NULL,
  `VatAmount2` TEXT NULL,
  `VatAmount3` TEXT NULL,
  `OtherAmount1` TEXT NULL,
  `OtherAmount2` TEXT NULL,
  `OtherAmount3` TEXT NULL,
  `OtherDecAmount1` TEXT NULL,
  `OtherDecAmount2` TEXT NULL,
  `OtherDecAmount3` TEXT NULL,
  `createdByJob` TEXT NULL,
  `changedByJob` TEXT NULL,
  `idBillingrule` TEXT NULL,
  `jsonDetail` TEXT NULL
);

-- summary_affected: the REAL outbox DDL (mirror of src/main/resources/sql/summary_outbox.sql).
CREATE TABLE IF NOT EXISTS summary_affected (
  id          BIGINT       NOT NULL AUTO_INCREMENT,
  entity_type VARCHAR(32)  NOT NULL,
  op          ENUM('add','subtract') NOT NULL DEFAULT 'add',
  data        LONGTEXT     NOT NULL,
  PRIMARY KEY (id),
  KEY ix_entity (entity_type, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
